# Generated by Django 4.1.2 on 2022-11-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id_number', models.UUIDField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneNumber', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('place', models.ManyToManyField(to='backend.place')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id_number', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('place', models.ManyToManyField(to='backend.place')),
                ('renter', models.ManyToManyField(to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ManyToManyField(to='backend.user'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('place', models.ManyToManyField(to='backend.place')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Characteristic', models.CharField(max_length=200)),
                ('id_number', models.ManyToManyField(to='backend.place')),
            ],
        ),
    ]
