# Generated by Django 4.1.2 on 2022-11-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='id_number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='id_number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_number',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='characteristics',
            name='id',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='id',
            field=models.ManyToManyField(to='backend.place'),
        ),
    ]
